language: python
python:
  - "2.7"
  - "3.3" 
  - "3.4"
  - "3.5"

addons:
  apt:
    packages:
    - graphviz

install: 
  - bash scripts/build_travis.sh

script:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source activate myenv
  - python -m nose --with-coverage

after_success:
  - coveralls
